Update windowed_wordcount.py
based on the ValueError I get if I provide it in the stated format.

File "/usr/local/lib/python2.7/dist-packages/apache_beam/io/gcp/pubsub.py", line 107, in parse_topic
    '/<topic>" (got %r).' % full_topic)
ValueError: PubSub topic must be in the form "projects/<project>/topics/<topic>"

The same change needs to be made to the other samples.